pipeline:
  build-and-push:
    image: plugins/docker
    group: publish_image
    registery: https://registry.swarm.sntestlab.com
    repo: registry.swarm.sntestlab.com/hackathon-team-c
    dockerfile: docker/Dockerfile
    context: .
    tags: 1.0.${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

  deploy:
    image: appleboy/drone-ssh
    host: swarm.sharpnotions.local
    username: sndocker
    secrets: [ ssh_password ]
    command_timeout: 600
    script:
      - docker service update --detach=false --image=registry.swarm.sntestlab.com/hackathon-team-c:1.0.${DRONE_BUILD_NUMBER} --restart-max-attempts 10 hackathon-team-c
    when:
      branch: master
      event: push

  notify:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: hackathon
    username: drone
    icon_url: https://discourse.drone.io/uploads/drone/original/1X/3c1169460330cd8c88c9da925e7bbbd7ace83200.png
    secrets: [ slack_webhook ]
    when:
      branch: master
      status: [ success, failure]
    template: >
      {{#success build.status}}
        [#{{ build.number }} {{ build.event }}] {{ repo.owner }}/{{ repo.name }} ({{ build.author }}, {{ build.commit }}), build succeeded and deployed to staging. :tada:  {{ build.link }}
      {{else}}
        [#{{ build.number }} {{ build.event }}] {{ repo.owner }}/{{ repo.name }} ({{ build.author }}, {{ build.commit }}), build Failed. :skull:  {{ build.link }}
      {{/success}}